# Use a base image with Node.js
FROM node:18

# Set the working directory
WORKDIR /app/api

# Copy package.json and package-lock.json to the container
COPY package*.json ./
COPY yarn.lock ./

# Install dependencies
RUN yarn install

# Copy the rest of the application files
COPY . .

# Expose the port the server runs on
EXPOSE 4000

# Command to run the server
CMD ["npm", "start"]
