name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  TOKEN_KEY: ${{ secrets.TOKEN_KEY }}
  EMAIL: ${{ secrets.EMAIL }}
  PASSWORD: ${{ secrets.PASSWORD }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install and Test Client
        working-directory: ./app/client
        run: |
          cd client
          yarn install
          yarn test

      - name: Install and Test Server
        working-directory: ./app/api
        run: |
          cd api
          npm install
          export MONGODB_URI=$MONGODB_URI
          export TOKEN_KEY=$TOKEN_KEY
          export EMAIL=$EMAIL
          export PASSWORD=$PASSWORD
          npm test

      - name: Build Client Docker Image
        working-directory: ./app/client
        run: |
          docker build -t akashwani2209/blogfootballapp-client:${{github.run_number}} .

      - name: Build Server Docker Image
        working-directory: ./app/api
        run: |
          docker build -t akashwani2209/blogfootballapp-api:${{github.run_number}} .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Images to Docker Hub
        run: |
          docker push akashwani2209/blogfootballapp-client:${{github.run_number}}
          docker push akashwani2209/blogfootballapp-api:${{github.run_number}}
